[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True

[/Script/GameplayTags.GameplayTagsList]
; --- Built-in gift tags provided by the plugin ---

GameplayTagList=(Tag="Gift.musiconstage",DevComment="")
GameplayTagList=(Tag="Gift.rose",DevComment="")
GameplayTagList=(Tag="Gift.gg",DevComment="")
GameplayTagList=(Tag="Gift.youreawesome",DevComment="")
GameplayTagList=(Tag="Gift.loveyousomuch",DevComment="")
GameplayTagList=(Tag="Gift.tiktok",DevComment="")
GameplayTagList=(Tag="Gift.icecreamcone",DevComment="")
GameplayTagList=(Tag="Gift.heartme",DevComment="")
GameplayTagList=(Tag="Gift.thumbsup",DevComment="")
GameplayTagList=(Tag="Gift.heart",DevComment="")
GameplayTagList=(Tag="Gift.lightningbolt",DevComment="")
GameplayTagList=(Tag="Gift.cakeslice",DevComment="")
GameplayTagList=(Tag="Gift.loveyou",DevComment="")
GameplayTagList=(Tag="Gift.itscorn",DevComment="")
GameplayTagList=(Tag="Gift.chili",DevComment="")
GameplayTagList=(Tag="Gift.heartpuff",DevComment="")
GameplayTagList=(Tag="Gift.goat",DevComment="")
GameplayTagList=(Tag="Gift.imnewhere",DevComment="")
GameplayTagList=(Tag="Gift.iheartyou",DevComment="")
GameplayTagList=(Tag="Gift.winkcharm",DevComment="")
GameplayTagList=(Tag="Gift.gopopular",DevComment="")
GameplayTagList=(Tag="Gift.clubcheers",DevComment="")
GameplayTagList=(Tag="Gift.teambracelet",DevComment="")
GameplayTagList=(Tag="Gift.fingerheart",DevComment="")
GameplayTagList=(Tag="Gift.hifriend",DevComment="")
GameplayTagList=(Tag="Gift.cheeryouup",DevComment="")
GameplayTagList=(Tag="Gift.clubpower",DevComment="")
GameplayTagList=(Tag="Gift.friendshipnecklace",DevComment="")
GameplayTagList=(Tag="Gift.rosa",DevComment="")
GameplayTagList=(Tag="Gift.journeypass",DevComment="")
GameplayTagList=(Tag="Gift.tinydiny",DevComment="")
GameplayTagList=(Tag="Gift.hibear",DevComment="")
GameplayTagList=(Tag="Gift.ewc",DevComment="")
GameplayTagList=(Tag="Gift.dolphin",DevComment="")
GameplayTagList=(Tag="Gift.banana",DevComment="")
GameplayTagList=(Tag="Gift.heartgaze",DevComment="")
GameplayTagList=(Tag="Gift.perfume",DevComment="")
GameplayTagList=(Tag="Gift.letemcook",DevComment="")
GameplayTagList=(Tag="Gift.tinydinyhotdog",DevComment="")
GameplayTagList=(Tag="Gift.doughnut",DevComment="")
GameplayTagList=(Tag="Gift.adventure",DevComment="")
GameplayTagList=(Tag="Gift.papercrane",DevComment="")
GameplayTagList=(Tag="Gift.littlecrown",DevComment="")
GameplayTagList=(Tag="Gift.cap",DevComment="")
GameplayTagList=(Tag="Gift.hatandmustache",DevComment="")
GameplayTagList=(Tag="Gift.likepop",DevComment="")
GameplayTagList=(Tag="Gift.heartmeflex",DevComment="")
GameplayTagList=(Tag="Gift.lovepainting",DevComment="")
GameplayTagList=(Tag="Gift.bubblegum",DevComment="")
GameplayTagList=(Tag="Gift.markoflove",DevComment="")
GameplayTagList=(Tag="Gift.rockthestage",DevComment="")
GameplayTagList=(Tag="Gift.star",DevComment="")
GameplayTagList=(Tag="Gift.clubvictory",DevComment="")
GameplayTagList=(Tag="Gift.levelupsparks",DevComment="")
GameplayTagList=(Tag="Gift.greetingheart",DevComment="")
GameplayTagList=(Tag="Gift.gamecontroller",DevComment="")
GameplayTagList=(Tag="Gift.supergg",DevComment="")
GameplayTagList=(Tag="Gift.confetti",DevComment="")
GameplayTagList=(Tag="Gift.handhearts",DevComment="")
GameplayTagList=(Tag="Gift.handheart",DevComment="")
GameplayTagList=(Tag="Gift.singingmagic",DevComment="")
GameplayTagList=(Tag="Gift.marvelousconfetti",DevComment="")
GameplayTagList=(Tag="Gift.heartrain",DevComment="")
GameplayTagList=(Tag="Gift.bowknot",DevComment="")
GameplayTagList=(Tag="Gift.bigshoutout",DevComment="")
GameplayTagList=(Tag="Gift.chattingpopcorn",DevComment="")
GameplayTagList=(Tag="Gift.mysterymask",DevComment="")
GameplayTagList=(Tag="Gift.heartballoons",DevComment="")
GameplayTagList=(Tag="Gift.lovecharger",DevComment="")
GameplayTagList=(Tag="Gift.sunglasses",DevComment="")
GameplayTagList=(Tag="Gift.hearts",DevComment="")
GameplayTagList=(Tag="Gift.hanginglights",DevComment="")
GameplayTagList=(Tag="Gift.garlandheadpiece",DevComment="")
GameplayTagList=(Tag="Gift.cheerforyou",DevComment="")
GameplayTagList=(Tag="Gift.pantherpaws",DevComment="")
GameplayTagList=(Tag="Gift.stingingbee",DevComment="")
GameplayTagList=(Tag="Gift.massageforyou",DevComment="")
GameplayTagList=(Tag="Gift.safarihat",DevComment="")
GameplayTagList=(Tag="Gift.coffeemagic",DevComment="")
GameplayTagList=(Tag="Gift.meerkat",DevComment="")
GameplayTagList=(Tag="Gift.potatoinparis",DevComment="")
GameplayTagList=(Tag="Gift.cheeringcrab",DevComment="")
GameplayTagList=(Tag="Gift.nightstar",DevComment="")
GameplayTagList=(Tag="Gift.woolyhat",DevComment="")
GameplayTagList=(Tag="Gift.blowbubbles",DevComment="")
GameplayTagList=(Tag="Gift.floatingoctopus",DevComment="")
GameplayTagList=(Tag="Gift.flowerheadband",DevComment="")
GameplayTagList=(Tag="Gift.bowtifulcrown",DevComment="")
GameplayTagList=(Tag="Gift.sourbuddy",DevComment="")
GameplayTagList=(Tag="Gift.shibainu",DevComment="")
GameplayTagList=(Tag="Gift.musicplayer",DevComment="")
GameplayTagList=(Tag="Gift.rilakkumasear",DevComment="")
GameplayTagList=(Tag="Gift.goldmedal",DevComment="")
GameplayTagList=(Tag="Gift.ilovetiktoklive",DevComment="")
GameplayTagList=(Tag="Gift.tinydinytrek",DevComment="")
GameplayTagList=(Tag="Gift.rosebear",DevComment="")
GameplayTagList=(Tag="Gift.pinchface",DevComment="")
GameplayTagList=(Tag="Gift.candybouquet",DevComment="")
GameplayTagList=(Tag="Gift.stargoggles",DevComment="")
GameplayTagList=(Tag="Gift.cheermic",DevComment="")
GameplayTagList=(Tag="Gift.bubbleheadphones",DevComment="")
GameplayTagList=(Tag="Gift.gamer2025",DevComment="")
GameplayTagList=(Tag="Gift.boxinggloves",DevComment="")
GameplayTagList=(Tag="Gift.corgi",DevComment="")
GameplayTagList=(Tag="Gift.fruitfriends",DevComment="")
GameplayTagList=(Tag="Gift.naughtychicken",DevComment="")
GameplayTagList=(Tag="Gift.playforyou",DevComment="")
GameplayTagList=(Tag="Gift.rockstar",DevComment="")
GameplayTagList=(Tag="Gift.butterflyforyou",DevComment="")
GameplayTagList=(Tag="Gift.puppykisses",DevComment="")
GameplayTagList=(Tag="Gift.risingkey",DevComment="")
GameplayTagList=(Tag="Gift.legendcrown",DevComment="")
GameplayTagList=(Tag="Gift.unitedheart",DevComment="")
GameplayTagList=(Tag="Gift.liverankingcrown",DevComment="")
GameplayTagList=(Tag="Gift.kickerchallenge",DevComment="")
GameplayTagList=(Tag="Gift.journal",DevComment="")
GameplayTagList=(Tag="Gift.rosieslook",DevComment="")
GameplayTagList=(Tag="Gift.buddingheart",DevComment="")
GameplayTagList=(Tag="Gift.feathermask",DevComment="")
GameplayTagList=(Tag="Gift.backingmonkey",DevComment="")
GameplayTagList=(Tag="Gift.kittenheadband",DevComment="")
GameplayTagList=(Tag="Gift.colorfultrailing",DevComment="")
GameplayTagList=(Tag="Gift.foreverrosa",DevComment="")
GameplayTagList=(Tag="Gift.magicrhythm",DevComment="")
GameplayTagList=(Tag="Gift.relaxedgoose",DevComment="")
GameplayTagList=(Tag="Gift.tomshug",DevComment="")
GameplayTagList=(Tag="Gift.rosietherosebean",DevComment="")
GameplayTagList=(Tag="Gift.jolliethejoybean",DevComment="")
GameplayTagList=(Tag="Gift.rockytherockbean",DevComment="")
GameplayTagList=(Tag="Gift.sagethesmartbean",DevComment="")
GameplayTagList=(Tag="Gift.sagesslash",DevComment="")
GameplayTagList=(Tag="Gift.letbutterflydances",DevComment="")
GameplayTagList=(Tag="Gift.kittenkneading",DevComment="")
GameplayTagList=(Tag="Gift.shoottheapple",DevComment="")
GameplayTagList=(Tag="Gift.alienbuddy",DevComment="")
GameplayTagList=(Tag="Gift.pharaohmask",DevComment="")
GameplayTagList=(Tag="Gift.rosiessaxophone",DevComment="")
GameplayTagList=(Tag="Gift.crystaldreams",DevComment="")
GameplayTagList=(Tag="Gift.wishingcake",DevComment="")
GameplayTagList=(Tag="Gift.micchamp",DevComment="")
GameplayTagList=(Tag="Gift.bouncespeakers",DevComment="")
GameplayTagList=(Tag="Gift.taraxacumcorgi",DevComment="")
GameplayTagList=(Tag="Gift.beatingheart",DevComment="")
GameplayTagList=(Tag="Gift.encoreclap",DevComment="")
GameplayTagList=(Tag="Gift.fairymask",DevComment="")
GameplayTagList=(Tag="Gift.powerfulmind",DevComment="")
GameplayTagList=(Tag="Gift.hatofjoy",DevComment="")
GameplayTagList=(Tag="Gift.pandahug",DevComment="")
GameplayTagList=(Tag="Gift.coral",DevComment="")
GameplayTagList=(Tag="Gift.sakuracorgi",DevComment="")
GameplayTagList=(Tag="Gift.handsup",DevComment="")
GameplayTagList=(Tag="Gift.moneygun",DevComment="")
GameplayTagList=(Tag="Gift.youreamazing",DevComment="")
GameplayTagList=(Tag="Gift.vrgoggles",DevComment="")
GameplayTagList=(Tag="Gift.manifesting",DevComment="")
GameplayTagList=(Tag="Gift.djglasses",DevComment="")
GameplayTagList=(Tag="Gift.dragoncrown",DevComment="")
GameplayTagList=(Tag="Gift.starmappolaris",DevComment="")
GameplayTagList=(Tag="Gift.bouquet",DevComment="")
GameplayTagList=(Tag="Gift.racinghelmet",DevComment="")
GameplayTagList=(Tag="Gift.prince",DevComment="")
GameplayTagList=(Tag="Gift.bunnyhat",DevComment="")
GameplayTagList=(Tag="Gift.heartitout",DevComment="")
GameplayTagList=(Tag="Gift.gemgun",DevComment="")
GameplayTagList=(Tag="Gift.radiantwings",DevComment="")
GameplayTagList=(Tag="Gift.swan",DevComment="")
GameplayTagList=(Tag="Gift.colorfulwings",DevComment="")
GameplayTagList=(Tag="Gift.trashpanda",DevComment="")
GameplayTagList=(Tag="Gift.bearblindbox",DevComment="")
GameplayTagList=(Tag="Gift.train",DevComment="")
GameplayTagList=(Tag="Gift.superstar",DevComment="")
GameplayTagList=(Tag="Gift.travelwithyou",DevComment="")
GameplayTagList=(Tag="Gift.luckyairdropbox",DevComment="")
GameplayTagList=(Tag="Gift.trendingfigure",DevComment="")
GameplayTagList=(Tag="Gift.goldmine",DevComment="")
GameplayTagList=(Tag="Gift.watermelonlove",DevComment="")
GameplayTagList=(Tag="Gift.dinosaur",DevComment="")
GameplayTagList=(Tag="Gift.glowingjellyfish",DevComment="")
GameplayTagList=(Tag="Gift.bloomingribbons",DevComment="")
GameplayTagList=(Tag="Gift.giraffe",DevComment="")
GameplayTagList=(Tag="Gift.galaxy",DevComment="")
GameplayTagList=(Tag="Gift.fairywings",DevComment="")
GameplayTagList=(Tag="Gift.flamingogroove",DevComment="")
GameplayTagList=(Tag="Gift.cooperbaseball",DevComment="")
GameplayTagList=(Tag="Gift.superlivestar",DevComment="")
GameplayTagList=(Tag="Gift.sparkledance",DevComment="")
GameplayTagList=(Tag="Gift.shinyairballoon",DevComment="")
GameplayTagList=(Tag="Gift.fireworks",DevComment="")
GameplayTagList=(Tag="Gift.diamond",DevComment="")
GameplayTagList=(Tag="Gift.travelintheus",DevComment="")
GameplayTagList=(Tag="Gift.umbrellaoflove",DevComment="")
GameplayTagList=(Tag="Gift.starlightsceptre",DevComment="")
GameplayTagList=(Tag="Gift.vibrantstage",DevComment="")
GameplayTagList=(Tag="Gift.chasingthedream",DevComment="")
GameplayTagList=(Tag="Gift.loverslock",DevComment="")
GameplayTagList=(Tag="Gift.greetingcard",DevComment="")
GameplayTagList=(Tag="Gift.futureencounter",DevComment="")
GameplayTagList=(Tag="Gift.ewctrophy",DevComment="")
GameplayTagList=(Tag="Gift.undercontrol",DevComment="")
GameplayTagList=(Tag="Gift.racingdebut",DevComment="")
GameplayTagList=(Tag="Gift.galaxyglobe",DevComment="")
GameplayTagList=(Tag="Gift.bloomingheart",DevComment="")
GameplayTagList=(Tag="Gift.herewego",DevComment="")
GameplayTagList=(Tag="Gift.lovedrop",DevComment="")
GameplayTagList=(Tag="Gift.ninetailedfox",DevComment="")
GameplayTagList=(Tag="Gift.rilakkumadance",DevComment="")
GameplayTagList=(Tag="Gift.starofredcarpet",DevComment="")
GameplayTagList=(Tag="Gift.giftbox",DevComment="")
GameplayTagList=(Tag="Gift.cooperflieshome",DevComment="")
GameplayTagList=(Tag="Gift.mysteryfirework",DevComment="")
GameplayTagList=(Tag="Gift.boxingglove",DevComment="")
GameplayTagList=(Tag="Gift.babydragon",DevComment="")
GameplayTagList=(Tag="Gift.crystalcrown",DevComment="")
GameplayTagList=(Tag="Gift.cooperpicnic",DevComment="")
GameplayTagList=(Tag="Gift.squeezetheday",DevComment="")
GameplayTagList=(Tag="Gift.whalediving",DevComment="")
GameplayTagList=(Tag="Gift.blowrosiekisses",DevComment="")
GameplayTagList=(Tag="Gift.jolliesheartland",DevComment="")
GameplayTagList=(Tag="Gift.rockyspunch",DevComment="")
GameplayTagList=(Tag="Gift.sagescoinbot",DevComment="")
GameplayTagList=(Tag="Gift.animalband",DevComment="")
GameplayTagList=(Tag="Gift.sleepykitty",DevComment="")
GameplayTagList=(Tag="Gift.concert",DevComment="")
GameplayTagList=(Tag="Gift.motorcycle",DevComment="")
GameplayTagList=(Tag="Gift.grandprixstage",DevComment="")
GameplayTagList=(Tag="Gift.rhythmicbear",DevComment="")
GameplayTagList=(Tag="Gift.goldieinbloom",DevComment="")
GameplayTagList=(Tag="Gift.lenossascommunitycake",DevComment="")
GameplayTagList=(Tag="Gift.levelupspotlight",DevComment="")
GameplayTagList=(Tag="Gift.meteorshower",DevComment="")
GameplayTagList=(Tag="Gift.heartstage",DevComment="")
GameplayTagList=(Tag="Gift.yourconcert",DevComment="")
GameplayTagList=(Tag="Gift.privatejet",DevComment="")
GameplayTagList=(Tag="Gift.leonthekitten",DevComment="")
GameplayTagList=(Tag="Gift.fierydragon",DevComment="")
GameplayTagList=(Tag="Gift.signaturejet",DevComment="")
GameplayTagList=(Tag="Gift.knockout",DevComment="")
GameplayTagList=(Tag="Gift.tomslove",DevComment="")
GameplayTagList=(Tag="Gift.sagesventure",DevComment="")
GameplayTagList=(Tag="Gift.unicornfantasy",DevComment="")
GameplayTagList=(Tag="Gift.flyingjets",DevComment="")
GameplayTagList=(Tag="Gift.diamondgun",DevComment="")
GameplayTagList=(Tag="Gift.wolf",DevComment="")
GameplayTagList=(Tag="Gift.devotedheart",DevComment="")
GameplayTagList=(Tag="Gift.futurecity",DevComment="")
GameplayTagList=(Tag="Gift.saminnewcity",DevComment="")
GameplayTagList=(Tag="Gift.workhardplayharder",DevComment="")
GameplayTagList=(Tag="Gift.strongfinish",DevComment="")
GameplayTagList=(Tag="Gift.ellieinthewild",DevComment="")
GameplayTagList=(Tag="Gift.ruffrider",DevComment="")
GameplayTagList=(Tag="Gift.lilitheleopard",DevComment="")
GameplayTagList=(Tag="Gift.happyparty",DevComment="")
GameplayTagList=(Tag="Gift.sportscar",DevComment="")
GameplayTagList=(Tag="Gift.varsitysquad",DevComment="")
GameplayTagList=(Tag="Gift.starthrone",DevComment="")
GameplayTagList=(Tag="Gift.safaripark",DevComment="")
GameplayTagList=(Tag="Gift.leonandlili",DevComment="")
GameplayTagList=(Tag="Gift.aquarius",DevComment="")
GameplayTagList=(Tag="Gift.interstellar",DevComment="")
GameplayTagList=(Tag="Gift.sunsetspeedway",DevComment="")
GameplayTagList=(Tag="Gift.luxuryyacht",DevComment="")
GameplayTagList=(Tag="Gift.rilakkumassummervacation",DevComment="")
GameplayTagList=(Tag="Gift.redlightning",DevComment="")
GameplayTagList=(Tag="Gift.convertible",DevComment="")
GameplayTagList=(Tag="Gift.levelupspectacle",DevComment="")
GameplayTagList=(Tag="Gift.fatesphere",DevComment="")
GameplayTagList=(Tag="Gift.chronorewinder",DevComment="")
GameplayTagList=(Tag="Gift.crystalheart",DevComment="")
GameplayTagList=(Tag="Gift.brancastle",DevComment="")
GameplayTagList=(Tag="Gift.leopard",DevComment="")
GameplayTagList=(Tag="Gift.rosanebula",DevComment="")
GameplayTagList=(Tag="Gift.pyramids",DevComment="")
GameplayTagList=(Tag="Gift.futurejourney",DevComment="")
GameplayTagList=(Tag="Gift.partyonon",DevComment="")
GameplayTagList=(Tag="Gift.battlechampion",DevComment="")
GameplayTagList=(Tag="Gift.tailsinflight",DevComment="")
GameplayTagList=(Tag="Gift.heartsuperstage",DevComment="")
GameplayTagList=(Tag="Gift.amusementpark",DevComment="")
GameplayTagList=(Tag="Gift.flylove",DevComment="")
GameplayTagList=(Tag="Gift.tiktokshuttle",DevComment="")
GameplayTagList=(Tag="Gift.castlefantasy",DevComment="")
GameplayTagList=(Tag="Gift.premiumshuttle",DevComment="")
GameplayTagList=(Tag="Gift.infiniteheart",DevComment="")
GameplayTagList=(Tag="Gift.vhsplayer",DevComment="")
GameplayTagList=(Tag="Gift.stellarark",DevComment="")
GameplayTagList=(Tag="Gift.lightcastle",DevComment="")
GameplayTagList=(Tag="Gift.phoenix",DevComment="")
GameplayTagList=(Tag="Gift.adamsdream",DevComment="")
GameplayTagList=(Tag="Gift.dragonflame",DevComment="")
GameplayTagList=(Tag="Gift.lion",DevComment="")
GameplayTagList=(Tag="Gift.leonandlion",DevComment="")
GameplayTagList=(Tag="Gift.zeus",DevComment="")
GameplayTagList=(Tag="Gift.tiktokuniverseplus",DevComment="")
GameplayTagList=(Tag="Gift.tiktokstars",DevComment="")
GameplayTagList=(Tag="Gift.thunderfalcon",DevComment="")
GameplayTagList=(Tag="Gift.firephoenix",DevComment="")
GameplayTagList=(Tag="Gift.magicmarcia",DevComment="")
GameplayTagList=(Tag="Gift.kingleonardo",DevComment="")
GameplayTagList=(Tag="Gift.pegasus",DevComment="")
GameplayTagList=(Tag="Gift.tiktokuniverse",DevComment="")

; …add ~300 lines here…
; Syntax: GameplayTagList=(Tag="Gift.<lowercase_no_spaces_or_punct>",DevComment="<optional>")
